on:
  - push

name: CI-CD TESTING

jobs:
  deploy:
    name: Push image
    runs-on: ubuntu-18.04
    env:
      API_IMAGE_TAG: ${GITHUB_SHA:1:7}
      REPO: ${{ secrets.ECR_REGISTRY_URL }}/${{ secrets.REPOSITORY }}
    steps:
      - name: Configure AWS ECR credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_ACCESS_KEY_SECRET }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: push Docker image
        run: |
          docker build -f Dockerfile \
            -t ${REPO}:STG-${GITHUB_SHA:1:7} .
          docker tag ${REPO}:STG-${GITHUB_SHA:1:7} ${REPO}:master
          docker push ${REPO}:master
